workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      groups:
        - android
      flutter: stable
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
