class ComplaintModel {
      String id;
        String userId;
          String userName;
            String title;
              String description;
                String status; // pending, processing, resolved, rejected
                  String? response;
                    DateTime createdAt;
                      DateTime? updatedAt;
                        List<String>? attachments;
                          String? priority; // low, medium, high

                            ComplaintModel({
                                required this.id,
                                    required this.userId,
                                        required this.userName,
                                            required this.title,
                                                required this.description,
                                                    required this.status,
                                                        this.response,
                                                            required this.createdAt,
                                                                this.updatedAt,
                                                                    this.attachments,
                                                                        this.priority = 'medium',
                                                                          });

                                                                            Map<String, dynamic> toMap() {
                                                                                return {
                                                                                      'id': id,
                                                                                            'userId': userId,
                                                                                                  'userName': userName,
                                                                                                        'title': title,
                                                                                                              'description': description,
                                                                                                                    'status': status,
                                                                                                                          'response': response,
                                                                                                                                'createdAt': createdAt.toIso8601String(),
                                                                                                                                      'updatedAt': updatedAt?.toIso8601String(),
                                                                                                                                            'attachments': attachments,
                                                                                                                                                  'priority': priority,
                                                                                                                                                      };
                                                                                                                                                        }

                                                                                                                                                          factory ComplaintModel.fromMap(Map<String, dynamic> map) {
                                                                                                                                                              return ComplaintModel(
                                                                                                                                                                    id: map['id'] ?? '',
                                                                                                                                                                          userId: map['userId'] ?? '',
                                                                                                                                                                                userName: map['userName'] ?? '',
                                                                                                                                                                                      title: map['title'] ?? '',
                                                                                                                                                                                            description: map['description'] ?? '',
                                                                                                                                                                                                  status: map['status'] ?? 'pending',
                                                                                                                                                                                                        response: map['response'],
                                                                                                                                                                                                              createdAt: map['createdAt'] != null 
                                                                                                                                                                                                                        ? DateTime.parse(map['createdAt']) 
                                                                                                                                                                                                                                  : DateTime.now(),
                                                                                                                                                                                                                                        updatedAt: map['updatedAt'] != null 
                                                                                                                                                                                                                                                  ? DateTime.parse(map['updatedAt']) 
                                                                                                                                                                                                                                                            : null,
                                                                                                                                                                                                                                                                  attachments: List<String>.from(map['attachments'] ?? []),
                                                                                                                                                                                                                                                                        priority: map['priority'] ?? 'medium',
                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                  Color get statusColor {
                                                                                                                                                                                                                                                                                      switch (status) {
                                                                                                                                                                                                                                                                                            case 'pending':
                                                                                                                                                                                                                                                                                                    return const Color(0xfff59e0b);
                                                                                                                                                                                                                                                                                                          case 'processing':
                                                                                                                                                                                                                                                                                                                  return const Color(0xff3b82f6);
                                                                                                                                                                                                                                                                                                                        case 'resolved':
                                                                                                                                                                                                                                                                                                                                return const Color(0xff10b981);
                                                                                                                                                                                                                                                                                                                                      case 'rejected':
                                                                                                                                                                                                                                                                                                                                              return const Color(0xffef4444);
                                                                                                                                                                                                                                                                                                                                                    default:
                                                                                                                                                                                                                                                                                                                                                            return const Color(0xff9ca3af);
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                      String get statusText {
                                                                                                                                                                                                                                                                                                                                                                          switch (status) {
                                                                                                                                                                                                                                                                                                                                                                                case 'pending':
                                                                                                                                                                                                                                                                                                                                                                                        return 'قيد الانتظار';
                                                                                                                                                                                                                                                                                                                                                                                              case 'processing':
                                                                                                                                                                                                                                                                                                                                                                                                      return 'قيد المعالجة';
                                                                                                                                                                                                                                                                                                                                                                                                            case 'resolved':
                                                                                                                                                                                                                                                                                                                                                                                                                    return 'تم الحل';
                                                                                                                                                                                                                                                                                                                                                                                                                          case 'rejected':
                                                                                                                                                                                                                                                                                                                                                                                                                                  return 'مرفوض';
                                                                                                                                                                                                                                                                                                                                                                                                                                        default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                return 'غير معروف';
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
}