class UserModel {
      String userId;
        String name;
          String phone;
            String role;
              String status;
                String? agentId;
                  double balance;
                    String? photoUrl;
                      String? fcmToken;
                        DateTime? createdAt;
                          DateTime? lastLogin;
                            String? nationalId;
                              String? address;
                                int? contributionsCount;
                                  double? totalContributions;

                                    UserModel({
                                        required this.userId,
                                            required this.name,
                                                required this.phone,
                                                    required this.role,
                                                        required this.status,
                                                            this.agentId,
                                                                required this.balance,
                                                                    this.photoUrl,
                                                                        this.fcmToken,
                                                                            this.createdAt,
                                                                                this.lastLogin,
                                                                                    this.nationalId,
                                                                                        this.address,
                                                                                            this.contributionsCount,
                                                                                                this.totalContributions,
                                                                                                  });

                                                                                                    Map<String, dynamic> toMap() {
                                                                                                        return {
                                                                                                              'userId': userId,
                                                                                                                    'name': name,
                                                                                                                          'phone': phone,
                                                                                                                                'role': role,
                                                                                                                                      'status': status,
                                                                                                                                            'agentId': agentId,
                                                                                                                                                  'balance': balance,
                                                                                                                                                        'photoUrl': photoUrl,
                                                                                                                                                              'fcmToken': fcmToken,
                                                                                                                                                                    'createdAt': createdAt?.toIso8601String() ?? DateTime.now().toIso8601String(),
                                                                                                                                                                          'lastLogin': lastLogin?.toIso8601String(),
                                                                                                                                                                                'nationalId': nationalId,
                                                                                                                                                                                      'address': address,
                                                                                                                                                                                            'contributionsCount': contributionsCount ?? 0,
                                                                                                                                                                                                  'totalContributions': totalContributions ?? 0,
                                                                                                                                                                                                      };
                                                                                                                                                                                                        }

                                                                                                                                                                                                          factory UserModel.fromMap(Map<String, dynamic> map) {
                                                                                                                                                                                                              return UserModel(
                                                                                                                                                                                                                    userId: map['userId'] ?? '',
                                                                                                                                                                                                                          name: map['name'] ?? '',
                                                                                                                                                                                                                                phone: map['phone'] ?? '',
                                                                                                                                                                                                                                      role: map['role'] ?? 'contributor',
                                                                                                                                                                                                                                            status: map['status'] ?? 'pending',
                                                                                                                                                                                                                                                  agentId: map['agentId'],
                                                                                                                                                                                                                                                        balance: (map['balance'] ?? 0).toDouble(),
                                                                                                                                                                                                                                                              photoUrl: map['photoUrl'],
                                                                                                                                                                                                                                                                    fcmToken: map['fcmToken'],
                                                                                                                                                                                                                                                                          createdAt: map['createdAt'] != null ? DateTime.parse(map['createdAt']) : null,
                                                                                                                                                                                                                                                                                lastLogin: map['lastLogin'] != null ? DateTime.parse(map['lastLogin']) : null,
                                                                                                                                                                                                                                                                                      nationalId: map['nationalId'],
                                                                                                                                                                                                                                                                                            address: map['address'],
                                                                                                                                                                                                                                                                                                  contributionsCount: map['contributionsCount'] ?? 0,
                                                                                                                                                                                                                                                                                                        totalContributions: (map['totalContributions'] ?? 0).toDouble(),
                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                  // نسخة محدثة
                                                                                                                                                                                                                                                                                                                    UserModel copyWith({
                                                                                                                                                                                                                                                                                                                        String? userId,
                                                                                                                                                                                                                                                                                                                            String? name,
                                                                                                                                                                                                                                                                                                                                String? phone,
                                                                                                                                                                                                                                                                                                                                    String? role,
                                                                                                                                                                                                                                                                                                                                        String? status,
                                                                                                                                                                                                                                                                                                                                            String? agentId,
                                                                                                                                                                                                                                                                                                                                                double? balance,
                                                                                                                                                                                                                                                                                                                                                    String? photoUrl,
                                                                                                                                                                                                                                                                                                                                                        String? fcmToken,
                                                                                                                                                                                                                                                                                                                                                            DateTime? createdAt,
                                                                                                                                                                                                                                                                                                                                                                DateTime? lastLogin,
                                                                                                                                                                                                                                                                                                                                                                    String? nationalId,
                                                                                                                                                                                                                                                                                                                                                                        String? address,
                                                                                                                                                                                                                                                                                                                                                                            int? contributionsCount,
                                                                                                                                                                                                                                                                                                                                                                                double? totalContributions,
                                                                                                                                                                                                                                                                                                                                                                                  }) {
                                                                                                                                                                                                                                                                                                                                                                                      return UserModel(
                                                                                                                                                                                                                                                                                                                                                                                            userId: userId ?? this.userId,
                                                                                                                                                                                                                                                                                                                                                                                                  name: name ?? this.name,
                                                                                                                                                                                                                                                                                                                                                                                                        phone: phone ?? this.phone,
                                                                                                                                                                                                                                                                                                                                                                                                              role: role ?? this.role,
                                                                                                                                                                                                                                                                                                                                                                                                                    status: status ?? this.status,
                                                                                                                                                                                                                                                                                                                                                                                                                          agentId: agentId ?? this.agentId,
                                                                                                                                                                                                                                                                                                                                                                                                                                balance: balance ?? this.balance,
                                                                                                                                                                                                                                                                                                                                                                                                                                      photoUrl: photoUrl ?? this.photoUrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                            fcmToken: fcmToken ?? this.fcmToken,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  createdAt: createdAt ?? this.createdAt,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        lastLogin: lastLogin ?? this.lastLogin,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              nationalId: nationalId ?? this.nationalId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    address: address ?? this.address,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          contributionsCount: contributionsCount ?? this.contributionsCount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                totalContributions: totalContributions ?? this.totalContributions,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
}