import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/user_model.dart';
import '../constants/app_constants.dart';

class AuthService {
  final FirebaseAuth _auth = FirebaseAuth.instance;
    final FirebaseFirestore _firestore = FirebaseFirestore.instance;
      
        String? _verificationId;
          
            // التحقق من رقم الجوال
              Future<void> verifyPhoneNumber({
                  required String phoneNumber,
                      required Function(String verificationId) onCodeSent,
                          required Function(FirebaseAuthException error) onError,
                            }) async {
                                await _auth.verifyPhoneNumber(
                                      phoneNumber: phoneNumber,
                                            verificationCompleted: (PhoneAuthCredential credential) async {
                                                    await signInWithCredential(credential);
                                                          },
                                                                verificationFailed: (FirebaseAuthException e) {
                                                                        onError(e);
                                                                              },
                                                                                    codeSent: (String verificationId, int? resendToken) {
                                                                                            _verificationId = verificationId;
                                                                                                    onCodeSent(verificationId);
                                                                                                          },
                                                                                                                codeAutoRetrievalTimeout: (String verificationId) {
                                                                                                                        _verificationId = verificationId;
                                                                                                                              },
                                                                                                                                  );
                                                                                                                                    }
                                                                                                                                      
                                                                                                                                        // تسجيل الدخول باستخدام OTP
                                                                                                                                          Future<UserCredential> signInWithOTP({
                                                                                                                                              required String verificationId,
                                                                                                                                                  required String smsCode,
                                                                                                                                                    }) async {
                                                                                                                                                        PhoneAuthCredential credential = PhoneAuthProvider.credential(
                                                                                                                                                              verificationId: verificationId,
                                                                                                                                                                    smsCode: smsCode,
                                                                                                                                                                        );
                                                                                                                                                                            return await signInWithCredential(credential);
                                                                                                                                                                              }
                                                                                                                                                                                
                                                                                                                                                                                  // تسجيل الدخول باستخدام بيانات الاعتماد
                                                                                                                                                                                    Future<UserCredential> signInWithCredential(PhoneAuthCredential credential) async {
                                                                                                                                                                                        UserCredential userCredential = await _auth.signInWithCredential(credential);
                                                                                                                                                                                            
                                                                                                                                                                                                // تحديث آخر تسجيل دخول
                                                                                                                                                                                                    if (userCredential.user != null) {
                                                                                                                                                                                                          await _firestore.collection(AppConstants.usersCollection)
                                                                                                                                                                                                                    .doc(userCredential.user!.uid)
                                                                                                                                                                                                                              .update({
                                                                                                                                                                                                                                      'lastLogin': DateTime.now().toIso8601String(),
                                                                                                                                                                                                                                              'fcmToken': await _getFCMToken(),
                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                // حفظ معلومات المستخدم محلياً
                                                                                                                                                                                                                                                                      await _saveUserSession(userCredential.user!.uid);
                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                  return userCredential;
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                        // تسجيل الخروج
                                                                                                                                                                                                                                                                                          Future<void> signOut() async {
                                                                                                                                                                                                                                                                                              await _auth.signOut();
                                                                                                                                                                                                                                                                                                  final prefs = await SharedPreferences.getInstance();
                                                                                                                                                                                                                                                                                                      await prefs.clear();
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                            // الحصول على المستخدم الحالي
                                                                                                                                                                                                                                                                                                              User? getCurrentUser() {
                                                                                                                                                                                                                                                                                                                  return _auth.currentUser;
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                        // التحقق من وجود مستخدم مسجل الدخول
                                                                                                                                                                                                                                                                                                                          bool isLoggedIn() {
                                                                                                                                                                                                                                                                                                                              return _auth.currentUser != null;
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                    // حفظ جلسة المستخدم
                                                                                                                                                                                                                                                                                                                                      Future<void> _saveUserSession(String userId) async {
                                                                                                                                                                                                                                                                                                                                          final prefs = await SharedPreferences.getInstance();
                                                                                                                                                                                                                                                                                                                                              await prefs.setBool('isLoggedIn', true);
                                                                                                                                                                                                                                                                                                                                                  await prefs.setString('userId', userId);
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                        // الحصول على دور المستخدم من Firebase
                                                                                                                                                                                                                                                                                                                                                          Future<String?> getUserRole(String userId) async {
                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                    DocumentSnapshot doc = await _firestore
                                                                                                                                                                                                                                                                                                                                                                              .collection(AppConstants.usersCollection)
                                                                                                                                                                                                                                                                                                                                                                                        .doc(userId)
                                                                                                                                                                                                                                                                                                                                                                                                  .get();
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                              if (doc.exists) {
                                                                                                                                                                                                                                                                                                                                                                                                                      return doc.get('role');
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                      print('Error getting user role: $e');
                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                              return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                    // الحصول على بيانات المستخدم
                                                                                                                                                                                                                                                                                                                                                                                                                                                      Future<UserModel?> getUserData(String userId) async {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                DocumentSnapshot doc = await _firestore
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .collection(AppConstants.usersCollection)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .doc(userId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .get();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (doc.exists) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return UserModel.fromMap(doc.data() as Map<String, dynamic>);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  print('Error getting user data: $e');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // الحصول على FCM Token
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Future<String?> _getFCMToken() async {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // سيتم تنفيذها مع خدمة الإشعارات
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // تغيير كلمة المرور (للمستخدمين الذين يستخدمون البريد الإلكتروني)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Future<void> changePassword(String newPassword) async {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      User? user = _auth.currentUser;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (user != null && user.email != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await user.updatePassword(newPassword);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // حذف حساب المستخدم
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Future<void> deleteAccount() async {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                User? user = _auth.currentUser;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (user != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await user.delete();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }